# refer to https://blog.dejavu.moe/posts/build-passkeys-identity-system-with-pocketid-x-tinyauth/#联合身份验证
location /<Path> {
    # Leave <Path> blank to protect root path.
    proxy_pass http://<Need Authentication Host>:<Port>/<Path>;
    auth_request /tinyauth;
    error_page 401 = @tinyauth_login;
}

location /tinyauth {
    proxy_pass http://127.0.0.1:30001/api/auth/nginx;
    proxy_set_header x-forwarded-proto $scheme;
    proxy_set_header x-forwarded-host $http_host;
    proxy_set_header x-forwarded-uri $request_uri;
}

location @tinyauth_login {
    return 302 https://tinyauth.your.domain/login?redirect_uri=$scheme://$http_host$request_uri;
}